/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LawyerRouteImport } from './routes/lawyer'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminLawyersRouteImport } from './routes/admin.lawyers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSendOtpRouteImport } from './routes/api/send-otp'
import { Route as ApiVerifyOtpRouteImport } from './routes/api/verify-otp'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientBookingsRouteImport } from './routes/client.bookings'
import { Route as ClientDocumentsRouteImport } from './routes/client.documents'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientPaymentsRouteImport } from './routes/client.payments'
import { Route as ClientReviewsRouteImport } from './routes/client.reviews'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as LawyerIndexRouteImport } from './routes/lawyer.index'
import { Route as LawyerClientsRouteImport } from './routes/lawyer.clients'
import { Route as LawyerDocumentsRouteImport } from './routes/lawyer.documents'
import { Route as LawyerEarningsRouteImport } from './routes/lawyer.earnings'
import { Route as LawyerScheduleRouteImport } from './routes/lawyer.schedule'
import { Route as LawyerSettingsRouteImport } from './routes/lawyer.settings'
import { Route as AuthRoleLoginRouteImport } from './routes/auth.$role.login'
import { Route as AuthRoleRegisterRouteImport } from './routes/auth.$role.register'
import { Route as ClientBookLawyerIdRouteImport } from './routes/client.book.$lawyerId'
import { Route as ClientLawyersIndexRouteImport } from './routes/client.lawyers.index'
import { Route as ClientLawyersLawyerIdRouteImport } from './routes/client.lawyers.$lawyerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRoute = LawyerRouteImport.update({
  id: '/lawyer',
  path: '/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyersRoute = AdminLawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendOtpRoute = ApiSendOtpRouteImport.update({
  id: '/api/send-otp',
  path: '/api/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyOtpRoute = ApiVerifyOtpRouteImport.update({
  id: '/api/verify-otp',
  path: '/api/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ClientRoute,
} as any)
const ClientReviewsRoute = ClientReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const LawyerIndexRoute = LawyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerClientsRoute = LawyerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerDocumentsRoute = LawyerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerEarningsRoute = LawyerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerScheduleRoute = LawyerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerSettingsRoute = LawyerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LawyerRoute,
} as any)
const AuthRoleLoginRoute = AuthRoleLoginRouteImport.update({
  id: '/auth/$role/login',
  path: '/auth/$role/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRegisterRoute = AuthRoleRegisterRouteImport.update({
  id: '/auth/$role/register',
  path: '/auth/$role/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBookLawyerIdRoute = ClientBookLawyerIdRouteImport.update({
  id: '/book/$lawyerId',
  path: '/book/$lawyerId',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLawyersIndexRoute = ClientLawyersIndexRouteImport.update({
  id: '/lawyers/',
  path: '/lawyers/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLawyersLawyerIdRoute = ClientLawyersLawyerIdRouteImport.update({
  id: '/lawyers/$lawyerId',
  path: '/lawyers/$lawyerId',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/lawyer': typeof LawyerRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/lawyer/clients': typeof LawyerClientsRoute
  '/lawyer/documents': typeof LawyerDocumentsRoute
  '/lawyer/earnings': typeof LawyerEarningsRoute
  '/lawyer/schedule': typeof LawyerScheduleRoute
  '/lawyer/settings': typeof LawyerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/lawyer/': typeof LawyerIndexRoute
  '/auth/$role/login': typeof AuthRoleLoginRoute
  '/auth/$role/register': typeof AuthRoleRegisterRoute
  '/client/book/$lawyerId': typeof ClientBookLawyerIdRoute
  '/client/lawyers/$lawyerId': typeof ClientLawyersLawyerIdRoute
  '/client/lawyers/': typeof ClientLawyersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/lawyer/clients': typeof LawyerClientsRoute
  '/lawyer/documents': typeof LawyerDocumentsRoute
  '/lawyer/earnings': typeof LawyerEarningsRoute
  '/lawyer/schedule': typeof LawyerScheduleRoute
  '/lawyer/settings': typeof LawyerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/lawyer': typeof LawyerIndexRoute
  '/auth/$role/login': typeof AuthRoleLoginRoute
  '/auth/$role/register': typeof AuthRoleRegisterRoute
  '/client/book/$lawyerId': typeof ClientBookLawyerIdRoute
  '/client/lawyers/$lawyerId': typeof ClientLawyersLawyerIdRoute
  '/client/lawyers': typeof ClientLawyersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/lawyer': typeof LawyerRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/send-otp': typeof ApiSendOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/lawyer/clients': typeof LawyerClientsRoute
  '/lawyer/documents': typeof LawyerDocumentsRoute
  '/lawyer/earnings': typeof LawyerEarningsRoute
  '/lawyer/schedule': typeof LawyerScheduleRoute
  '/lawyer/settings': typeof LawyerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/lawyer/': typeof LawyerIndexRoute
  '/auth/$role/login': typeof AuthRoleLoginRoute
  '/auth/$role/register': typeof AuthRoleRegisterRoute
  '/client/book/$lawyerId': typeof ClientBookLawyerIdRoute
  '/client/lawyers/$lawyerId': typeof ClientLawyersLawyerIdRoute
  '/client/lawyers/': typeof ClientLawyersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/get-started'
    | '/lawyer'
    | '/admin/approvals'
    | '/admin/disputes'
    | '/admin/lawyers'
    | '/admin/settings'
    | '/admin/transactions'
    | '/api/chat'
    | '/api/health'
    | '/api/send-otp'
    | '/api/verify-otp'
    | '/client/bookings'
    | '/client/documents'
    | '/client/notifications'
    | '/client/payments'
    | '/client/reviews'
    | '/client/settings'
    | '/lawyer/clients'
    | '/lawyer/documents'
    | '/lawyer/earnings'
    | '/lawyer/schedule'
    | '/lawyer/settings'
    | '/admin/'
    | '/client/'
    | '/lawyer/'
    | '/auth/$role/login'
    | '/auth/$role/register'
    | '/client/book/$lawyerId'
    | '/client/lawyers/$lawyerId'
    | '/client/lawyers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/admin/approvals'
    | '/admin/disputes'
    | '/admin/lawyers'
    | '/admin/settings'
    | '/admin/transactions'
    | '/api/chat'
    | '/api/health'
    | '/api/send-otp'
    | '/api/verify-otp'
    | '/client/bookings'
    | '/client/documents'
    | '/client/notifications'
    | '/client/payments'
    | '/client/reviews'
    | '/client/settings'
    | '/lawyer/clients'
    | '/lawyer/documents'
    | '/lawyer/earnings'
    | '/lawyer/schedule'
    | '/lawyer/settings'
    | '/admin'
    | '/client'
    | '/lawyer'
    | '/auth/$role/login'
    | '/auth/$role/register'
    | '/client/book/$lawyerId'
    | '/client/lawyers/$lawyerId'
    | '/client/lawyers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/get-started'
    | '/lawyer'
    | '/admin/approvals'
    | '/admin/disputes'
    | '/admin/lawyers'
    | '/admin/settings'
    | '/admin/transactions'
    | '/api/chat'
    | '/api/health'
    | '/api/send-otp'
    | '/api/verify-otp'
    | '/client/bookings'
    | '/client/documents'
    | '/client/notifications'
    | '/client/payments'
    | '/client/reviews'
    | '/client/settings'
    | '/lawyer/clients'
    | '/lawyer/documents'
    | '/lawyer/earnings'
    | '/lawyer/schedule'
    | '/lawyer/settings'
    | '/admin/'
    | '/client/'
    | '/lawyer/'
    | '/auth/$role/login'
    | '/auth/$role/register'
    | '/client/book/$lawyerId'
    | '/client/lawyers/$lawyerId'
    | '/client/lawyers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  LawyerRoute: typeof LawyerRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSendOtpRoute: typeof ApiSendOtpRoute
  ApiVerifyOtpRoute: typeof ApiVerifyOtpRoute
  AuthRoleLoginRoute: typeof AuthRoleLoginRoute
  AuthRoleRegisterRoute: typeof AuthRoleRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer': {
      id: '/lawyer'
      path: '/lawyer'
      fullPath: '/lawyer'
      preLoaderRoute: typeof LawyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyers': {
      id: '/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof AdminLawyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-otp': {
      id: '/api/send-otp'
      path: '/api/send-otp'
      fullPath: '/api/send-otp'
      preLoaderRoute: typeof ApiSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-otp': {
      id: '/api/verify-otp'
      path: '/api/verify-otp'
      fullPath: '/api/verify-otp'
      preLoaderRoute: typeof ApiVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payments': {
      id: '/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientPaymentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/reviews': {
      id: '/client/reviews'
      path: '/reviews'
      fullPath: '/client/reviews'
      preLoaderRoute: typeof ClientReviewsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/lawyer/': {
      id: '/lawyer/'
      path: '/'
      fullPath: '/lawyer/'
      preLoaderRoute: typeof LawyerIndexRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/clients': {
      id: '/lawyer/clients'
      path: '/clients'
      fullPath: '/lawyer/clients'
      preLoaderRoute: typeof LawyerClientsRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/documents': {
      id: '/lawyer/documents'
      path: '/documents'
      fullPath: '/lawyer/documents'
      preLoaderRoute: typeof LawyerDocumentsRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/earnings': {
      id: '/lawyer/earnings'
      path: '/earnings'
      fullPath: '/lawyer/earnings'
      preLoaderRoute: typeof LawyerEarningsRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/schedule': {
      id: '/lawyer/schedule'
      path: '/schedule'
      fullPath: '/lawyer/schedule'
      preLoaderRoute: typeof LawyerScheduleRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/settings': {
      id: '/lawyer/settings'
      path: '/settings'
      fullPath: '/lawyer/settings'
      preLoaderRoute: typeof LawyerSettingsRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/auth/$role/login': {
      id: '/auth/$role/login'
      path: '/auth/$role/login'
      fullPath: '/auth/$role/login'
      preLoaderRoute: typeof AuthRoleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$role/register': {
      id: '/auth/$role/register'
      path: '/auth/$role/register'
      fullPath: '/auth/$role/register'
      preLoaderRoute: typeof AuthRoleRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/book/$lawyerId': {
      id: '/client/book/$lawyerId'
      path: '/book/$lawyerId'
      fullPath: '/client/book/$lawyerId'
      preLoaderRoute: typeof ClientBookLawyerIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/lawyers/': {
      id: '/client/lawyers/'
      path: '/lawyers'
      fullPath: '/client/lawyers/'
      preLoaderRoute: typeof ClientLawyersIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/lawyers/$lawyerId': {
      id: '/client/lawyers/$lawyerId'
      path: '/lawyers/$lawyerId'
      fullPath: '/client/lawyers/$lawyerId'
      preLoaderRoute: typeof ClientLawyersLawyerIdRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminLawyersRoute: typeof AdminLawyersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminLawyersRoute: AdminLawyersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientReviewsRoute: typeof ClientReviewsRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientBookLawyerIdRoute: typeof ClientBookLawyerIdRoute
  ClientLawyersLawyerIdRoute: typeof ClientLawyersLawyerIdRoute
  ClientLawyersIndexRoute: typeof ClientLawyersIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientPaymentsRoute: ClientPaymentsRoute,
  ClientReviewsRoute: ClientReviewsRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientBookLawyerIdRoute: ClientBookLawyerIdRoute,
  ClientLawyersLawyerIdRoute: ClientLawyersLawyerIdRoute,
  ClientLawyersIndexRoute: ClientLawyersIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface LawyerRouteChildren {
  LawyerClientsRoute: typeof LawyerClientsRoute
  LawyerDocumentsRoute: typeof LawyerDocumentsRoute
  LawyerEarningsRoute: typeof LawyerEarningsRoute
  LawyerScheduleRoute: typeof LawyerScheduleRoute
  LawyerSettingsRoute: typeof LawyerSettingsRoute
  LawyerIndexRoute: typeof LawyerIndexRoute
}

const LawyerRouteChildren: LawyerRouteChildren = {
  LawyerClientsRoute: LawyerClientsRoute,
  LawyerDocumentsRoute: LawyerDocumentsRoute,
  LawyerEarningsRoute: LawyerEarningsRoute,
  LawyerScheduleRoute: LawyerScheduleRoute,
  LawyerSettingsRoute: LawyerSettingsRoute,
  LawyerIndexRoute: LawyerIndexRoute,
}

const LawyerRouteWithChildren =
  LawyerRoute._addFileChildren(LawyerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  LawyerRoute: LawyerRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSendOtpRoute: ApiSendOtpRoute,
  ApiVerifyOtpRoute: ApiVerifyOtpRoute,
  AuthRoleLoginRoute: AuthRoleLoginRoute,
  AuthRoleRegisterRoute: AuthRoleRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
